# ============================================================
# PVRPWDP Generator for Env V2 (Mix 2 ONLY)
#   Mix 2: Solomon : MultiSlot = 6 : 4
#   - NO epoch / curriculum / phase logic (Env V2 doesn't pass epoch)
#   - Keep Near–Far drone-aware coordinate generation
#   - Keep demand-by-region logic BUT fixed to EASY settings (no epoch schedule)
#   - Keep TW pipeline but ONLY Solomon + MultiSlot rules
#
# Output TensorDict keys (compatible with env_v2_fixed.py / PVRPWDPV2Env):
#   locs: [B, N, 2]       (customers) normalized to [0,1]
#   depot: [B, 2]         normalized to [0,1]
#   demand: [B, N]        normalized by max_demand_global
#   time_windows: [B, N+1, 2] normalized time (same scale as travel_time)
#   endurance: [B]        normalized by T0
#   freshness: [B]        normalized by T0
#   num_trucks, num_drones: [B]
#   capacity_per_vehicle: [B, V]
#   speed_factor: [B, V]  (truck=1.0, drone=speed_truck/speed_drone)
# ============================================================

from __future__ import annotations

from typing import Optional
import math
import torch
from torch.distributions import Uniform
from tensordict.tensordict import TensorDict

from rl4co.envs.common.utils import Generator, get_sampler
from rl4co.utils.pylogger import get_pylogger

log = get_pylogger(__name__)


class PVRPWDPGenerator(Generator):
    def __init__(
        self,
        size_id: int = 1,
        speed_truck: float = 50.0,         # km/h
        speed_drone: float = 112.0,        # km/h
        min_demand: float = 0.1,
        max_demand: float = 50.0,
        max_demand_global: float = 200.0,  # normalize demand by this
        drone_endurance_raw: float = 0.2,  # hours
        freshness_raw: float = 1.0,        # hours
        truck_capacity: float = 1000.0,    # kg
        drone_capacity: float = 2.27,      # kg
        use_instance_profiles: bool = True,
        return_profile_id: bool = False,
        profile_probs: Optional[list[float]] = None,
        **kwargs,
    ):
        """
        Env V2 generator (Mix2 only):
        - All times in hours internally, then normalized by T0 = map_size / speed_truck (hours).
        - Travel-time scale in env: distance (in [0,1]) for truck; drone uses speed_factor.
        - time_windows are normalized (same scale as travel_time).
        - Near–Far coordinates are kept (drone-aware radius).
        - Demand near/far is kept but fixed to EASY (no epoch progression).
        - TW rules only: Solomon + MultiSlot with ratio 0.6 : 0.4
        """
        super().__init__(**kwargs)

        # ----------------------------------------------------------
        # Size config
        # ----------------------------------------------------------
        if size_id == 1:
            self.num_loc = 20
            self.num_trucks = 2
            self.num_drones = 2
            self.map_size = 35.0
            self.time_horizon_raw = 3.0  # hours (keep as your current config)
        else:
            raise ValueError(f"Unsupported size_id={size_id}. Only size_id=1 supported.")

        self.size_id = size_id

        self.speed_truck = float(speed_truck)
        self.speed_drone = float(speed_drone)
        self.min_demand = float(min_demand)
        self.max_demand = float(max_demand)
        self.max_demand_global = float(max_demand_global)
        self.drone_endurance_raw = float(drone_endurance_raw)
        self.freshness_raw = float(freshness_raw)
        self.truck_capacity = float(truck_capacity)
        self.drone_capacity = float(drone_capacity)

        # Samplers (kept for reproducibility hooks, though loc/demand are generated by custom logic)
        self.loc_sampler = get_sampler("loc", Uniform, 0.0, self.map_size, **kwargs)
        self.depot_sampler = get_sampler("depot", Uniform, 0.0, self.map_size, **kwargs)
        self.demand_sampler = get_sampler("demand", Uniform, min_demand, max_demand, **kwargs)

        # Normalize time by T0 = map_size / speed_truck (hours)
        self.T0 = self.map_size / self.speed_truck
        self.time_horizon = self.time_horizon_raw / self.T0
        self.max_makespan = float(self.time_horizon)

        # Penalties (kept)
        self.hard_penalty = math.ceil(self.max_makespan + 1.0)
        self.soft_penalty = 1.0

        # Mix2 definition only
        self.mix_id = 2
        self.mix_definitions = {
            2: {
                "Solomon": 0.6,
                "MultiSlot": 0.4,
            }
        }

        # ---------------------------
        # EASY fixed settings (no epoch)
        # ---------------------------
        self.p_near_easy = 0.5        # near ratio in coords
        self.q_heavy_near_easy = 0.03  # small chance of heavy demand even in near region

        # ---------------------------
        # Per-instance profile diversity (optional)
        # ---------------------------
        # To increase instance diversity *within the same generated epoch*, we sample one profile_id per instance.
        # This profile controls:
        #   - width_level distribution (tight/medium/wide) per customer node
        #   - truck_max_ratio (clamp width vs time_horizon) per width level
        #   - dronable slack delta range (minutes) for the "NEW TW RULE"
        #   - p_near and q_heavy_near (coords/demand)
        #
        # IMPORTANT:
        # - By default, we DO NOT change the TensorDict keys returned (unless return_profile_id=True).
        self.use_instance_profiles = bool(use_instance_profiles)
        self.return_profile_id = bool(return_profile_id)

        self.profile_names = ["tighter", "base", "loose1", "loose2", "very_loose"]
        self.profile_probs = profile_probs if profile_probs is not None else [0.10, 0.25, 0.25, 0.25, 0.15]

        # width_level probs per profile: [p_tight, p_medium, p_wide]
        self.width_level_probs_table = [
            [0.55, 0.40, 0.05],  # tighter
            [0.10, 0.80, 0.10],  # base (mostly medium, close to current)
            [0.20, 0.50, 0.30],  # loose1
            [0.10, 0.40, 0.50],  # loose2
            [0.05, 0.25, 0.70],  # very_loose
        ]

        # Truck TW max clamp ratios (relative to time_horizon) per profile and per width_level (tight/medium/wide)
        self.truck_max_ratio_table = [
            [0.10, 0.18, 0.30],  # tighter
            [0.15, 0.25, 0.40],  # base (current)
            [0.20, 0.35, 0.55],  # loose1
            [0.25, 0.45, 0.70],  # loose2
            [0.35, 0.60, 0.90],  # very_loose
        ]

        # Dronable TW slack delta range in minutes (per instance)
        self.dronable_delta_min_minute = [6.0, 12.0, 20.0, 30.0, 60.0]
        self.dronable_delta_max_minute = [12.0, 20.0, 35.0, 60.0, 120.0]

        # Coord / demand diversity (per instance)
        self.p_near_table = [0.45, 0.50, 0.60, 0.68, 0.75]
        self.q_heavy_near_table = [0.05, 0.03, 0.02, 0.01, 0.008]

    # ============================================================
    # Public API (Env V2 does not pass epoch)
    # ============================================================
    def __call__(self, batch_size, current_epoch: int = 0, max_epochs: Optional[int] = None) -> TensorDict:
        batch_size = [batch_size] if isinstance(batch_size, int) else batch_size
        return self._generate(batch_size, current_epoch=current_epoch, max_epochs=max_epochs)

    def _generate(self, batch_size, **kwargs) -> TensorDict:
        # Depot in [0,map_size] -> normalize to [0,1]
        depot_raw = self.depot_sampler.sample((*batch_size, 2))
        depot = depot_raw / self.map_size

        # Normalize time quantities by T0
        T0 = self.T0
        endurance = torch.full((*batch_size,), self.drone_endurance_raw / T0, dtype=torch.float32, device=depot.device)
        freshness = torch.full((*batch_size,), self.freshness_raw / T0, dtype=torch.float32, device=depot.device)
        time_horizon = self.time_horizon_raw / T0  # scalar (normalized)

        # ======================================================
        # Near–Far drone-aware coords (EASY fixed / profiled)
        # ======================================================
        # drone radius in normalized coordinates:
        # 2*a_drone <= endurance  <=> dist <= (endurance/2) * (v_drone/v_truck)
        r_norm = (endurance / 2.0) * (self.speed_drone / self.speed_truck)  # [B]

        # Sample one profile per instance (optional)
        profile_id = None
        if self.use_instance_profiles:
            B = batch_size[0]
            profile_id = self._sample_profile_ids(B, device=depot.device)  # [B]
            p_near = self._lookup_table_1d(self.p_near_table, profile_id, device=depot.device)  # [B]
            q_heavy = self._lookup_table_1d(self.q_heavy_near_table, profile_id, device=depot.device)  # [B]
        else:
            p_near = float(self.p_near_easy)
            q_heavy = float(self.q_heavy_near_easy)

        locs = self._sample_locs_near_far(
            depot=depot,
            r_norm=r_norm,
            p_near=p_near,
        )

        # Demand
        demand = self._sample_demand_near_far_easy(
            locs=locs,
            depot=depot,
            r_norm=r_norm,
            q_heavy=q_heavy,
        )

        # ======================================================
        # Time windows (Mix2 only)
        # ======================================================
        time_windows = self._generate_time_windows_mix2(
            depot=depot,
            locs=locs,
            time_horizon=time_horizon,
            endurance=endurance,
            profile_id=profile_id,
        )

        # Shape check
        B = batch_size[0]
        N = self.num_loc
        assert time_windows.shape == (B, N + 1, 2), \
            f"time_windows shape mismatch: expected ({B}, {N+1}, 2), got {time_windows.shape}"

        # Vehicles
        num_trucks = torch.full((*batch_size,), self.num_trucks, dtype=torch.long, device=depot.device)
        num_drones = torch.full((*batch_size,), self.num_drones, dtype=torch.long, device=depot.device)

        # capacity_per_vehicle and speed_factor
        capacity_per_vehicle = []
        speed_factors = []
        for i in range(B):
            n_truck = int(num_trucks[i].item())
            n_drone = int(num_drones[i].item())

            vt = torch.full((n_truck,), self.truck_capacity / self.max_demand_global, device=depot.device, dtype=torch.float32)
            vd = torch.full((n_drone,), self.drone_capacity / self.max_demand_global, device=depot.device, dtype=torch.float32)

            truck_sf = torch.ones(n_truck, device=depot.device, dtype=torch.float32)
            drone_sf = torch.full((n_drone,), self.speed_truck / self.speed_drone, device=depot.device, dtype=torch.float32)

            capacity_per_vehicle.append(torch.cat([vt, vd], dim=0))
            speed_factors.append(torch.cat([truck_sf, drone_sf], dim=0))

        capacity_per_vehicle = torch.stack(capacity_per_vehicle, dim=0)  # [B, V]
        speed_factor = torch.stack(speed_factors, dim=0)                 # [B, V]

        td_dict = {
            "locs": locs,
            "depot": depot,
            "demand": demand,
            "time_windows": time_windows,
            "endurance": endurance,
            "freshness": freshness,
            "num_trucks": num_trucks,
            "num_drones": num_drones,
            "capacity_per_vehicle": capacity_per_vehicle,
            "speed_factor": speed_factor,
        }
        # Keep backward-compatible TensorDict keys by default
        if self.return_profile_id and (profile_id is not None):
            td_dict["profile_id"] = profile_id

        return TensorDict(td_dict, batch_size=batch_size)

    # ============================================================
    # Profile helpers (per-instance diversity)
    # ============================================================
    def _sample_profile_ids(self, B: int, device: torch.device) -> torch.Tensor:
        probs = torch.tensor(self.profile_probs, device=device, dtype=torch.float32)
        probs = probs / probs.sum().clamp_min(1e-9)
        return torch.multinomial(probs, B, replacement=True)

    def _lookup_table_1d(
        self,
        table: list,
        profile_id: torch.Tensor,
        device: torch.device,
        dtype: torch.dtype = torch.float32,
    ) -> torch.Tensor:
        t = torch.tensor(table, device=device, dtype=dtype)
        return t[profile_id]

    def _lookup_table_2d(
        self,
        table: list,
        profile_id: torch.Tensor,
        device: torch.device,
        dtype: torch.dtype = torch.float32,
    ) -> torch.Tensor:
        t = torch.tensor(table, device=device, dtype=dtype)
        return t[profile_id]  # [B, K]

    def _sample_width_level_by_profile(
        self,
        B: int,
        N: int,
        profile_id: torch.Tensor,
        device: torch.device,
    ) -> torch.Tensor:
        """Sample width_level per customer node (1..N-1) using profile-specific categorical probs.
        width_level values: 0=tight, 1=medium, 2=wide. Depot (index 0) is set to 1 (medium).
        """
        probs_B3 = self._lookup_table_2d(self.width_level_probs_table, profile_id, device=device)  # [B, 3]
        dist = torch.distributions.Categorical(probs=probs_B3)
        wl_customers = dist.sample((N - 1,)).transpose(0, 1).contiguous()  # [B, N-1]
        wl = torch.full((B, N), 1, device=device, dtype=torch.long)
        wl[:, 1:] = wl_customers
        return wl

    # ============================================================
    # Coordinates: Near–Far (drone-aware)
    # ============================================================
    def _sample_locs_near_far(
        self,
        depot: torch.Tensor,     # [B, 2] normalized
        r_norm: torch.Tensor,    # [B] drone radius (normalized)
        p_near: float | torch.Tensor,  # float or [B] tensor
    ) -> torch.Tensor:
        """
        Two regions:
        - near: inside circle radius r_norm around depot
        - far : uniform on [0,1]^2
        """
        B = depot.size(0)
        N = self.num_loc
        device = depot.device
        locs = torch.empty((B, N, 2), device=device, dtype=torch.float32)

        for b in range(B):
            pnb = float(p_near[b].item()) if isinstance(p_near, torch.Tensor) else float(p_near)
            for i in range(N):
                if torch.rand(1, device=device).item() < pnb:
                    # sample in disk
                    while True:
                        rho = r_norm[b] * torch.sqrt(torch.rand(1, device=device))
                        theta = 2 * torch.pi * torch.rand(1, device=device)
                        x = depot[b, 0] + rho * torch.cos(theta)
                        y = depot[b, 1] + rho * torch.sin(theta)
                        if 0.0 <= float(x) <= 1.0 and 0.0 <= float(y) <= 1.0:
                            locs[b, i, 0] = x
                            locs[b, i, 1] = y
                            break
                else:
                    locs[b, i] = torch.rand(2, device=device, dtype=torch.float32)

        return locs

    # ============================================================
    # Demand: region-based (EASY fixed)
    # ============================================================
    def _sample_demand_near_far_easy(
        self,
        locs: torch.Tensor,      # [B, N, 2]
        depot: torch.Tensor,     # [B, 2]
        r_norm: torch.Tensor,    # [B]
        q_heavy: float | torch.Tensor,  # float or [B] tensor
        min_d: float = 0.1,
        near_light_max: float = 1.25,
        far_max: float = 49.0,
    ) -> torch.Tensor:
        """
        EASY fixed demand:
        - near: light demand in [min_d, near_light_max], with prob q_heavy use [near_light_max, far_max]
        - far : uniform in [min_d, far_max]
        Then normalize by max_demand_global (same as your original generator).
        """
        B, N, _ = locs.shape
        device = locs.device
        demand = torch.empty((B, N), device=device, dtype=torch.float32)

        for b in range(B):
            qhb = float(q_heavy[b].item()) if isinstance(q_heavy, torch.Tensor) else float(q_heavy)
            dist = torch.norm(locs[b] - depot[b], dim=-1)
            is_near = dist <= r_norm[b]
            for i in range(N):
                u = torch.rand(1, device=device).item()
                if bool(is_near[i]):
                    if u < qhb:
                        demand[b, i] = torch.rand(1, device=device) * (far_max - near_light_max) + near_light_max
                    else:
                        demand[b, i] = torch.rand(1, device=device) * (near_light_max - min_d) + min_d
                else:
                    demand[b, i] = torch.rand(1, device=device) * (far_max - min_d) + min_d

        return demand / self.max_demand_global

    # ============================================================
    # Time windows (Mix 2 only): Solomon + MultiSlot
    # ============================================================
    def _generate_time_windows_mix2(
        self,
        depot: torch.Tensor,        # [B,2]
        locs: torch.Tensor,         # [B,N,2]
        time_horizon: float,        # scalar normalized
        endurance: torch.Tensor,    # [B] normalized
        profile_id: Optional[torch.Tensor] = None,  # [B] optional
    ) -> torch.Tensor:
        """
        Pipeline kept from your v4-style TW generator, but restricted to:
        - Mix 2 (Solomon + MultiSlot)
        - No phase/epoch logic
        """
        a_truck, is_dronable = self._compute_travel_baselines(depot=depot, locs=locs, endurance=endurance)
        (w_unit_truck, w_unit_drone) = self._compute_instance_stats_v4(locs=locs, a_truck=a_truck)

        # mix_id fixed to 2
        node_groups = self._split_nodes_by_mix(mix_id=2, num_nodes=self.num_loc, device=locs.device)

        B, N = a_truck.shape
        device = a_truck.device

        center = torch.zeros((B, N), device=device, dtype=torch.float32)
        vehicle_bias = torch.zeros((B, N), dtype=torch.long, device=device)

        use_profile = (profile_id is not None) and self.use_instance_profiles

        if use_profile:
            # width_level sampled per-node per-instance
            width_level = self._sample_width_level_by_profile(B, N, profile_id, device=device)  # [B, N]
            # per-instance truck max ratios per width level: [B,3]
            truck_max_ratio_per_level = self._lookup_table_2d(self.truck_max_ratio_table, profile_id, device=device)
            # per-instance dronable delta ranges in minutes: [B]
            delta_min_minute = self._lookup_table_1d(self.dronable_delta_min_minute, profile_id, device=device)
            delta_max_minute = self._lookup_table_1d(self.dronable_delta_max_minute, profile_id, device=device)
        else:
            width_level = torch.zeros((B, N), dtype=torch.long, device=device)
            truck_max_ratio_per_level = None
            delta_min_minute = None
            delta_max_minute = None

        for rule_name, node_ids in node_groups.items():
            if node_ids.numel() == 0:
                continue
            if rule_name == "Solomon":
                self._apply_solomon(node_ids, a_truck, center, width_level, vehicle_bias, set_width_level=not use_profile)
            elif rule_name == "MultiSlot":
                self._apply_multislot(node_ids, a_truck, center, width_level, vehicle_bias, set_width_level=not use_profile)
            else:
                raise ValueError(f"Unexpected rule in Mix2-only generator: {rule_name}")

        width = self._realize_width_and_clamp_v4(
            width_level=width_level,
            vehicle_bias=vehicle_bias,
            w_unit_truck=w_unit_truck,
            w_unit_drone=w_unit_drone,
            endurance=endurance,
            time_horizon=time_horizon,
            truck_max_ratio_per_level=truck_max_ratio_per_level,
        )

        time_windows = self._finalize_time_windows_v4(
            center=center,
            width=width,
            a_truck=a_truck,
            node_groups=node_groups,
            time_horizon=time_horizon,
        )

        # ======================================================
        # TW RULE (re-designed):
        # Goal:
        #   - For dronable nodes: TW width in [20, 30] minutes
        #   - For non-dronable nodes: keep the previously-generated TW (or you can also
        #     set to [20, 40] if you want everything uniform)
        #
        # For dronable nodes, we create two modes per-node:
        #   (A) arrival is inside the window:  start <= a_truck <= end
        #   (B) window opens AFTER arrival:    start >= a_truck (with offset 1..8 minutes)
        #
        # This avoids the old (a_drone -/+ delta) rule that caused width inflation/deflation.
        # ======================================================

        th = time_horizon if isinstance(time_horizon, torch.Tensor) else torch.tensor(float(time_horizon), device=device)

        # widths for dronable nodes: Uniform(20, 30) minutes -> normalized
        W_dr = ((torch.rand((B, N), device=device, dtype=torch.float32) * (30.0 - 20.0) + 20.0) / 60.0) / max(self.T0, 1e-9)

        # current windows (customers only)
        tw_start = time_windows[:, 1:, 0]
        tw_end   = time_windows[:, 1:, 1]

        # truck & drone arrival (normalized)
        a_drone = a_truck * (self.speed_truck / self.speed_drone)  # [B, N]

        # choose mode per dronable node
        p_in = 0.6
        mode_in = (torch.rand((B, N), device=device) < p_in) & is_dronable

        # ---- Mode A (arrival inside TW): set end >= a_truck, then start=end-W
        u = torch.rand((B, N), device=device, dtype=torch.float32)
        end_in = a_truck + u * W_dr                 # a_truck in [start, end]
        start_in = end_in - W_dr

        # ---- Mode B (opens after arrival): start = a_truck + offset(1..8 minutes)
        offset_norm = ((torch.rand((B, N), device=device, dtype=torch.float32) * (8.0 - 1.0) + 1.0) / 60.0) / max(self.T0, 1e-9)
        start_af = a_truck + offset_norm
        end_af = start_af + W_dr

        # combine only for dronable nodes; non-dronable keep old tw_start/tw_end
        start_new = torch.where(mode_in, start_in, start_af)
        end_new   = torch.where(mode_in, end_in,   end_af)

        # mild safety: drone must be able to arrive before TW closes (for dronable nodes)
        eps = 1e-6
        end_new = torch.maximum(end_new, a_drone + eps)

        # keep within horizon while preserving width W_dr:
        # clamp end <= H then move start accordingly (preserve width)
        end_new = torch.minimum(end_new, th)
        start_new = torch.clamp(end_new - W_dr, min=0.0)

        # write back only for dronable nodes
        tw_start = torch.where(is_dronable, start_new, tw_start)
        tw_end   = torch.where(is_dronable, end_new,   tw_end)

        # final clamp + ensure start < end
        tw_start = torch.clamp(tw_start, min=0.0)
        tw_end   = torch.clamp(tw_end, max=th)
        tw_start = torch.minimum(tw_start, tw_end - eps)

        time_windows[:, 1:, 0] = tw_start
        time_windows[:, 1:, 1] = tw_end

        return time_windows

    # ------------------------------
    # Travel baselines + dronable
    # ------------------------------
    def _compute_travel_baselines(
        self,
        depot: torch.Tensor,      # [B,2]
        locs: torch.Tensor,       # [B,N,2]
        endurance: torch.Tensor,  # [B]
        eps: float = 1e-9,
    ):
        depot_xy = depot.unsqueeze(1)
        dist = (locs - depot_xy).norm(p=2, dim=-1).clamp_min(eps)  # [B,N]
        a_truck = dist
        a_drone = dist * (self.speed_truck / self.speed_drone)
        is_dronable = (2.0 * a_drone) <= endurance.unsqueeze(1)
        return a_truck, is_dronable

    # ------------------------------
    # Instance stats (unchanged)
    # ------------------------------
    def _compute_instance_stats_v4(
        self,
        locs: torch.Tensor,      # [B,N,2]
        a_truck: torch.Tensor,   # [B,N]
        k_nn: int = 3,
        L_ref: float = 20.0 / (2.0 + 0.2 * 2.0),
        g_min: float = 0.85,
        g_max: float = 1.25,
        eps: float = 1e-9,
    ):
        device = locs.device
        dtype = locs.dtype
        B, N, _ = locs.shape

        t_dc = torch.median(a_truck, dim=1).values

        dmat = torch.cdist(locs, locs, p=2)
        diag = torch.arange(N, device=device)
        dmat[:, diag, diag] = 1e9

        k = min(k_nn, max(1, N - 1))
        knn_dists = torch.topk(dmat, k=k, dim=-1, largest=False).values
        knn_med_per_node = torch.median(knn_dists, dim=-1).values
        t_nn = torch.median(knn_med_per_node, dim=1).values

        t_ref_truck = 0.5 * t_dc + 0.5 * t_nn
        speed_ratio = self.speed_truck / self.speed_drone
        t_ref_drone = t_ref_truck * speed_ratio

        T = float(self.num_trucks)
        D = float(self.num_drones)
        Ncust = float(self.num_loc)
        effective_servers = T + 0.2 * D
        L = Ncust / max(effective_servers, eps)

        L_tensor = torch.full((B,), L, device=device, dtype=dtype)
        Lref_tensor = torch.full((B,), L_ref, device=device, dtype=dtype)

        g_load = torch.sqrt((L_tensor / (Lref_tensor + eps)).clamp_min(eps))
        g_load = g_load.clamp(min=g_min, max=g_max)

        w_unit_truck = t_ref_truck * g_load
        w_unit_drone = t_ref_drone * g_load
        return (w_unit_truck, w_unit_drone)

    # ------------------------------
    # Split nodes by Mix2
    # ------------------------------
    def _split_nodes_by_mix(self, mix_id: int, num_nodes: int, device: torch.device):
        mix_cfg = self.mix_definitions[mix_id]
        perm = torch.randperm(num_nodes, device=device)

        node_groups = {}
        start = 0
        for rule_name, ratio in mix_cfg.items():
            cnt = int(round(ratio * num_nodes))
            end = min(start + cnt, num_nodes)
            if end > start:
                node_groups[rule_name] = perm[start:end]
            else:
                node_groups[rule_name] = torch.empty(0, dtype=torch.long, device=device)
            start = end

        if start < num_nodes:
            first_rule = next(iter(node_groups))
            node_groups[first_rule] = torch.cat([node_groups[first_rule], perm[start:]], dim=0)

        return node_groups

    # ------------------------------
    # Rules (Mix2 only)
    # ------------------------------
    def _apply_solomon(self, node_ids, a_truck, center, width_level, vehicle_bias, set_width_level: bool = True):
        center[:, node_ids] = a_truck[:, node_ids]
        if set_width_level:
            width_level[:, node_ids] = 1   # medium
        vehicle_bias[:, node_ids] = 2  # neutral

    def _apply_multislot(self, node_ids, a_truck, center, width_level, vehicle_bias, set_width_level: bool = True):
        # Mark as MultiSlot; actual early/late split is done in finalize
        center[:, node_ids] = a_truck[:, node_ids]
        if set_width_level:
            width_level[:, node_ids] = 1   # medium
        vehicle_bias[:, node_ids] = 2  # neutral

    # ------------------------------
    # Width clamp (unchanged)
    # ------------------------------
    def _realize_width_and_clamp_v4(
        self,
        width_level: torch.Tensor,   # [B,N]
        vehicle_bias: torch.Tensor,  # [B,N]
        w_unit_truck: torch.Tensor,  # [B]
        w_unit_drone: torch.Tensor,  # [B]
        endurance: torch.Tensor,     # [B]
        time_horizon: float | torch.Tensor,
        truck_max_ratio_per_level: Optional[torch.Tensor] = None,  # [B,3] for (tight,med,wide)
        m_drone: float = 4.0,
        eps: float = 1e-9,
    ):
        device = width_level.device
        B, N = width_level.shape

        factor_tight, factor_medium, factor_wide = 0.8, 1.0, 1.3
        factor = torch.empty((B, N), device=device, dtype=torch.float32)
        factor[width_level == 0] = factor_tight
        factor[width_level == 1] = factor_medium
        factor[width_level == 2] = factor_wide

        truck_min_minutes = torch.empty((B, N), device=device, dtype=torch.float32)
        truck_min_minutes[width_level == 0] = 12.0
        truck_min_minutes[width_level == 1] = 18.0
        truck_min_minutes[width_level == 2] = 30.0

        drone_min_minutes = torch.empty((B, N), device=device, dtype=torch.float32)
        drone_min_minutes[width_level == 0] = 10.0
        drone_min_minutes[width_level == 1] = 15.0
        drone_min_minutes[width_level == 2] = 20.0

        truck_min = (truck_min_minutes / 60.0) / max(self.T0, eps)
        drone_min = (drone_min_minutes / 60.0) / max(self.T0, eps)

        th = time_horizon if isinstance(time_horizon, torch.Tensor) else torch.tensor(float(time_horizon), device=device)

        if truck_max_ratio_per_level is None:
            truck_max_ratio = torch.empty((B, N), device=device, dtype=torch.float32)
            truck_max_ratio[width_level == 0] = 0.15
            truck_max_ratio[width_level == 1] = 0.25
            truck_max_ratio[width_level == 2] = 0.40
        else:
            # gather per-node ratio from per-instance table [B,3]
            idx = width_level.clamp(0, 2)
            truck_max_ratio = truck_max_ratio_per_level.gather(1, idx)
        truck_max = truck_max_ratio * th

        drone_max = (m_drone * endurance).unsqueeze(1).expand(B, N)

        w_truck = w_unit_truck.unsqueeze(1).expand(B, N)
        w_drone = w_unit_drone.unsqueeze(1).expand(B, N)
        is_drone_bias = (vehicle_bias == 1)

        width_raw = factor * torch.where(is_drone_bias, w_drone, w_truck)

        width_min = torch.where(is_drone_bias, drone_min, truck_min)
        width_max = torch.where(is_drone_bias, drone_max, truck_max)
        width_max = torch.maximum(width_max, width_min + eps)

        width = torch.clamp(width_raw, min=width_min, max=width_max)
        return width

    # ------------------------------
    # Finalize TW + MultiSlot Option A (unchanged)
    # ------------------------------
    def _finalize_time_windows_v4(
        self,
        center: torch.Tensor,        # [B,N]
        width: torch.Tensor,         # [B,N]
        a_truck: torch.Tensor,       # [B,N]
        node_groups: dict,
        time_horizon: float | torch.Tensor,
        eps: float = 1e-9,
    ):
        device = center.device
        B, N = center.shape

        if not isinstance(time_horizon, torch.Tensor):
            time_horizon = torch.tensor(float(time_horizon), device=device)

        tw_start = center - 0.5 * width
        tw_end = center + 0.5 * width

        if "MultiSlot" in node_groups:
            node_ids = node_groups["MultiSlot"]

            early_center = center[:, node_ids] - 0.3 * width[:, node_ids]
            late_center = center[:, node_ids] + 0.3 * width[:, node_ids]

            early_start = early_center - 0.5 * width[:, node_ids]
            early_end = early_center + 0.5 * width[:, node_ids]

            late_start = late_center - 0.5 * width[:, node_ids]
            late_end = late_center + 0.5 * width[:, node_ids]

            early_ok = early_end >= a_truck[:, node_ids]
            late_ok = late_end >= a_truck[:, node_ids]

            use_early = early_ok | (~late_ok)

            tw_start[:, node_ids] = torch.where(use_early, early_start, late_start)
            tw_end[:, node_ids] = torch.where(use_early, early_end, late_end)

        tw_end = torch.maximum(tw_end, a_truck + eps)

        tw_start = torch.clamp(tw_start, min=0.0)
        tw_end = torch.clamp(tw_end, max=time_horizon)

        tw_start = torch.minimum(tw_start, tw_end - eps)

        depot_tw = torch.zeros(B, 1, 2, device=device, dtype=tw_start.dtype)
        depot_tw[:, 0, 0] = 0.0
        depot_tw[:, 0, 1] = time_horizon

        customer_tw = torch.stack([tw_start, tw_end], dim=-1)
        time_windows = torch.cat([depot_tw, customer_tw], dim=1)
        return time_windows

